#!/usr/bin/env node
/**
 * Emit CSS custom properties from the palettes.
 *
 * Generated rather than hand-written for the same reason the swatch sheet is: a palette that
 * changes must not be able to disagree with the CSS built from it. Re-run after editing any
 * theme; CI checks the output is current.
 *
 * The source names every colour for what it MEANS -- success, error, warning -- rather than
 * for where it appears, which is why one palette can dress a terminal, an editor and a web
 * page without being re-picked for each.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const SRC = "cli";
const OUT = "css";

/** Source key -> CSS custom property. Anything unmapped is deliberately not exported. */
const MAP = {
  claude: "accent",
  suggestion: "accent-2",
  text: "fg",
  inactive: "dim",
  subtle: "edge",
  success: "ok",
  warning: "warn",
  error: "err",
  permission: "caution",
};

const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

/** Surfaces are not in the source, so they are derived from the palette's own base. */
const SURFACE = {
  dark: { bg: "#0c0c12", panel: "#14141d", raised: "#1b1b26" },
  light: { bg: "#f7f5f8", panel: "#ffffff", raised: "#f0edf2" },
};

mkdirSync(OUT, { recursive: true });

const themes = readdirSync(SRC)
  .filter((f) => f.endsWith(".json"))
  .map((f) => JSON.parse(readFileSync(join(SRC, f), "utf8")))
  .sort((a, b) => a.name.localeCompare(b.name));

for (const t of themes) {
  const base = t.base === "light" ? "light" : "dark";
  const o = t.overrides ?? {};
  const vars = Object.entries(MAP)
    .filter(([src]) => o[src])
    .map(([src, css]) => `  --${css}: ${o[src]};`);
  const surface = Object.entries(SURFACE[base]).map(([k, v]) => `  --${k}: ${v};`);

  const css = `/* ${t.name} — generated by scripts/css.mjs. Do not edit by hand. */
:root {
${surface.join("\n")}
${vars.join("\n")}
  --radius: 12px;
  color-scheme: ${base};
}
`;
  writeFileSync(join(OUT, `${slug(t.name)}.css`), css);
}

/**
 * Paired files, one dark palette and one light, switched by the reader's own preference.
 *
 * A page that only looks right in one theme is not finished, and shipping two separate
 * stylesheets to be chosen by hand is the version everyone forgets to update.
 */
const PAIRS = [
  ["twilight-comet", "wisteria-alley"],
  ["coral-horizon", "neko-lantern"],
  ["rain-lantern", "sakura-road"],
  ["amethyst-yokai", "cherry-blossom-dusk"],
  ["moonlit-village", "sakura-lake"],
];

const bodyOf = (slugName) => {
  const css = readFileSync(join(OUT, `${slugName}.css`), "utf8");
  const m = /:root \{([\s\S]*?)\}/.exec(css);
  if (!m) throw new Error(`No :root block in ${slugName}.css`);
  return m[1].replace(/\n\s*color-scheme:[^;]+;/, "").trimEnd();
};

for (const [dark, light] of PAIRS) {
  const out = `/* ${dark} + ${light} — generated by scripts/css.mjs. Do not edit by hand. */
:root {
  color-scheme: dark light;
${bodyOf(dark)}
}

@media (prefers-color-scheme: light) {
  :root {
${bodyOf(light).split("\n").map((l) => "  " + l).join("\n")}
  }
}
`;
  writeFileSync(join(OUT, `pair-${dark}.css`), out);
}

console.log(`Wrote ${themes.length} palettes and ${PAIRS.length} pairs to ${OUT}/`);
