#!/usr/bin/env node
/**
 * Emit CSS custom properties from the palettes.
 *
 * Generated rather than hand-written for the same reason the swatch sheet is: a palette that
 * changes must not be able to disagree with the CSS built from it. Re-run after editing any
 * theme; CI checks the output is current.
 *
 * The source names every colour for what it MEANS -- success, error, warning -- rather than
 * for where it appears, which is why one palette can dress a terminal, an editor and a web
 * page without being re-picked for each.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const SRC = "cli";
const OUT = "css";

/** Source key -> CSS custom property. Anything unmapped is deliberately not exported. */
const MAP = {
  claude: "accent",
  suggestion: "accent-2",
  text: "fg",
  inactive: "dim",
  subtle: "edge",
  success: "ok",
  warning: "warn",
  error: "err",
  permission: "caution",
};

const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

/**
 * Surfaces are TINTED TOWARD THE PALETTE'S OWN ACCENT.
 *
 * A fixed set of greys was the first version and it was wrong: the ground is most of what
 * you see, so identical surfaces make every palette look like the same theme with different
 * trim. Pulling the hue from the accent and desaturating hard gives each palette its own
 * near-black, or its own off-white, which is the part the eye actually reads as "a theme".
 */
function hueOf(hex) {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return 250;
  const n = parseInt(m[1], 16);
  const r = ((n >> 16) & 255) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min;
  if (d === 0) return 250;
  let h;
  if (max === r) h = ((g - b) / d) % 6;
  else if (max === g) h = (b - r) / d + 2;
  else h = (r - g) / d + 4;
  return Math.round(((h * 60) + 360) % 360);
}

/**
 * How much tint a hue can carry before it looks dirty.
 *
 * Warm and cool hues do not take the same saturation at low lightness. A blue at 26% reads
 * as night; an orange at 26% reads as mud. Warmth peaks around hue 30 and bottoms out around
 * 210, so the tint is scaled down as a hue approaches orange.
 */
function tintCeiling(h) {
  const warmth = (Math.cos(((h - 30) * Math.PI) / 180) + 1) / 2; // 1 at orange, 0 at teal
  return 1 - 0.62 * warmth; // orange keeps ~38% of the tint, blue keeps all of it
}

function surfaces(base, accent) {
  const h = hueOf(accent);
  const k = tintCeiling(h);
  const s = (n) => `${(n * k).toFixed(1)}%`;
  return base === "light"
    ? { bg: `hsl(${h} ${s(34)} 97%)`, panel: `hsl(${h} ${s(46)} 99.5%)`, raised: `hsl(${h} ${s(30)} 94%)` }
    : { bg: `hsl(${h} ${s(26)} 6.5%)`, panel: `hsl(${h} ${s(22)} 10.5%)`, raised: `hsl(${h} ${s(20)} 15%)` };
}

mkdirSync(OUT, { recursive: true });

const themes = readdirSync(SRC)
  .filter((f) => f.endsWith(".json"))
  .map((f) => JSON.parse(readFileSync(join(SRC, f), "utf8")))
  .sort((a, b) => a.name.localeCompare(b.name));

for (const t of themes) {
  const base = t.base === "light" ? "light" : "dark";
  const o = t.overrides ?? {};
  const vars = Object.entries(MAP)
    .filter(([src]) => o[src])
    .map(([src, css]) => `  --${css}: ${o[src]};`);
  const surface = Object.entries(surfaces(base, o.claude ?? "#8b7cf6")).map(([k, v]) => `  --${k}: ${v};`);

  const css = `/* ${t.name} - generated by scripts/css.mjs. Do not edit by hand. */
:root {
${surface.join("\n")}
${vars.join("\n")}
  --radius: 12px;
  color-scheme: ${base};
}
`;
  writeFileSync(join(OUT, `${slug(t.name)}.css`), css);
}

/**
 * Paired files, one dark palette and one light, switched by the reader's own preference.
 *
 * A page that only looks right in one theme is not finished, and shipping two separate
 * stylesheets to be chosen by hand is the version everyone forgets to update.
 */
const PAIRS = [
  ["twilight-comet", "wisteria-alley"],
  ["coral-horizon", "neko-lantern"],
  ["rain-lantern", "sakura-road"],
  ["amethyst-yokai", "cherry-blossom-dusk"],
  ["moonlit-village", "sakura-lake"],
];

const bodyOf = (slugName) => {
  const css = readFileSync(join(OUT, `${slugName}.css`), "utf8");
  const m = /:root \{([\s\S]*?)\}/.exec(css);
  if (!m) throw new Error(`No :root block in ${slugName}.css`);
  return m[1].replace(/\n\s*color-scheme:[^;]+;/, "").trimEnd();
};

for (const [dark, light] of PAIRS) {
  const out = `/* ${dark} + ${light} - generated by scripts/css.mjs. Do not edit by hand. */
:root {
  color-scheme: dark light;
${bodyOf(dark)}
}

@media (prefers-color-scheme: light) {
  :root {
${bodyOf(light).split("\n").map((l) => "  " + l).join("\n")}
  }
}
`;
  writeFileSync(join(OUT, `pair-${dark}.css`), out);
}

console.log(`Wrote ${themes.length} palettes and ${PAIRS.length} pairs to ${OUT}/`);
