#!/usr/bin/env node
/**
 * Build the specimen site out of `css/`, so the page cannot disagree with the system.
 *
 * Everything the page shows is read from the theme files themselves: the palette list, each
 * one's accents, whether it is light or dark, and the type pairings with the faces they name.
 * A palette added to css/ appears here without anyone remembering to list it, which is the
 * failure this repository keeps writing tooling to avoid.
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { paletteFiles } from "./palettes.mjs";

/** The stylesheets the specimen page itself loads. A list of what it needs, not of what a
 *  palette is not - which is the distinction that made this the same list twice. */
const SHARED = ["base.css", "layout-flat.css", "motion.css", "texture.css"];
const files = readdirSync("css").filter((f) => f.endsWith(".css"));
// What counts as a palette lives in scripts/palettes.mjs. By elimination it was every file
// that is not a pair, a type pairing, or one of a listed four - which stopped being true the
// moment css/ gained a stylesheet for the picker.
const singles = paletteFiles("css", { singles: true }).map((name) => `${name}.css`);
const types = files.filter((f) => f.startsWith("type-"));

if (singles.length === 0) {
  console.error("no palettes found in css/, which cannot be right");
  process.exit(1);
}

const readVar = (body, token) => (body.match(new RegExp(`--${token}:\\s*([^;]+)`)) ?? [])[1]?.trim() ?? null;
const bodyOf = (src) => src.slice(src.indexOf("{") + 1, src.lastIndexOf("}"));
const title = (id) => id.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join(" ");

const palettes = singles
  .map((f) => {
    const body = bodyOf(readFileSync(`css/${f}`, "utf8"));
    const id = f.replace(/\.css$/, "");
    const bg = readVar(body, "bg");
    if (!bg) {
      console.error(`${f} has no --bg, so its scheme cannot be worked out`);
      process.exit(1);
    }
    return {
      id,
      label: title(id),
      accent: readVar(body, "accent"),
      accent2: readVar(body, "accent-2"),
      ok: readVar(body, "ok"),
      warn: readVar(body, "warn"),
      err: readVar(body, "err"),
      // Lightness is the last percentage in the hsl(). These are generated files, so the shape
      // is reliable, and reading it means a palette added later classifies itself.
      scheme: Number((bg.match(/([\d.]+)%\s*\)?\s*$/) ?? [])[1] ?? 0) > 50 ? "light" : "dark",
    };
  })
  .sort((a, b) => (a.scheme === b.scheme ? a.label.localeCompare(b.label) : a.scheme === "dark" ? -1 : 1));

const pairings = types.map((f) => {
  const src = readFileSync(`css/${f}`, "utf8");
  return {
    id: f.replace(/^type-|\.css$/g, ""),
    title: (src.match(/\/\*\s*([^\n]+)/) ?? [])[1]?.trim() ?? f,
    // The prose in each type file explains the choice. The first paragraph is the reason.
    why: (src.match(/\n\n\s{3}([^*]+?)\n\n/) ?? [])[1]?.replace(/\s+/g, " ").trim() ?? "",
    load: (src.match(/Load:\s*(\S+)/) ?? [])[1] ?? null,
    display: (src.match(/--font-display:\s*"([^"]+)"/) ?? [])[1] ?? null,
    body: (src.match(/--font-body:\s*"([^"]+)"/) ?? [])[1] ?? null,
    mono: (src.match(/--font-mono:\s*"([^"]+)"/) ?? [])[1] ?? null,
  };
});

mkdirSync("site/theme", { recursive: true });
writeFileSync(
  "site/theme/palettes.css",
  `/* Generated by scripts/site.mjs from css/*.css. Do not edit; edit the palette and re-run. */\n\n` +
    singles.map((f) => `[data-theme="${f.replace(/\.css$/, "")}"] {${bodyOf(readFileSync(`css/${f}`, "utf8"))}}`).join("\n\n") +
    "\n",
);
for (const f of [...SHARED, ...types]) copyFileSync(`css/${f}`, `site/theme/${f}`);
writeFileSync("site/data.json", JSON.stringify({ palettes, pairings }, null, 2) + "\n");

console.log(`${palettes.length} palettes (${palettes.filter((p) => p.scheme === "dark").length} dark, ${palettes.filter((p) => p.scheme === "light").length} light), ${pairings.length} type pairings`);
